#app
server:
    port: 8021

#spring
spring:
  devtools:
    restart:
      enabled: false

#rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: nico
    password: nico
    #发送消息确认回调
    publisher-returns: true
    publisher-confirms: true
    #发送消息确认方式
    #listener:
    #  simple:
    #    acknowledge-mode: manual
